#!/bin/bash

#day_str="2 days ago"
day_str="now"
#mon_str="1 month ago"
mon_str="now"

day_end=`date -d "$day_str" "+%d"`
#day_start=$day_end  #just for today.
day_start=1          #from the beginning of this month.

date_mon=`date -d "$mon_str" "+%m"`
date_year=`date +%Y`

for day in $(seq $day_start $day_end)
do
    d=`printf "%02d" $day`
    date_tmp="$date_year-$date_mon-$d"
    hits=`grep -nr 'PosReq' ~/tmp/log/wpp.log* |grep "$date_tmp" |wc -l` 
    day_of_week=`date -d "$date_tmp" +%u`
    printf '%-10s_%s,%8d\n' $date_tmp $day_of_week $hits
done
