#!/bin/bash
# connect remote bluetooth serial port device.
bt_dev_name=yxt-e71

btinit=/etc/init.d/bluetooth
btdaemon=`which bluetoothd`

btcomportid=0
btcomport=rfcomm$btcomportid
btcomdev=/dev/$btcomport

echo
[ "`pskill -l $btdaemon`" = "" ] \
	&& (echo "starting $btdaemon..."; sudo $btinit start) \
	|| echo "$btdaemon running!"
echo -e "\nScanning hci dev [$bt_dev_name]..."
echo "------------------------------"
bt_dev_mac=`hcitool scan |grep ${bt_dev_name} |awk '{print $1}'`
channel=`sdptool search SP |grep Channel |awk '{print $2}'`

[ "$bt_dev_mac" = "" -o "$channel" = "" ] && (echo "Failed! Exiting..."; exit 99)
printf "%8s: %-20s\n%8s: %-20s\n\n" "MAC Addr" ${bt_dev_mac} "Channel" $channel


if [ "`ls $btcomdev 2> /dev/null`" = "$btcomdev" ]; then
    echo "releasing $btcomport..."
    sudo rfcomm release $btcomportid 
fi 
echo "Binding $btcomport..."
retmsg=`sudo rfcomm bind $btcomportid ${bt_dev_mac} $channel 2>&1 |grep "Address already in use"`
if [ "$retmsg" = "" ]; then
	echo "Done"
else
	echo $retmsg; echo "Retry..."
	sudo rfcomm release $btcomportid
	sleep 1
	sudo rfcomm bind $btcomportid ${bt_dev_mac} $channel
fi

#rfcomm0 device identification for Pyserial.
#sudo rm /dev/ttyS0 -f && sudo ln -s /dev/rfcomm0 /dev/ttyS0
#ls -l /dev/ttyS0
