#!/bin/bash
# picking up test cases(lines) from reqreterr($1) which have different pos/err results between cpp/python.

awk -F, '
BEGIN {
    OFS=","
} 
{
    ep_cpp_py = $15; ee_cpp_py = $16
	print ep_cpp_py, ee_cpp_py
    if (ep_cpp_py > 10 || ee_cpp_py > 10){
        print
    }
} ' $1 |grep -v 'NaN'
