#!/bin/bash
# $0 <total reqs> <concurrent reqs> <target id>

ntot=$1
[ "$ntot" = "" ] && ntot=1
ncon=$2
[ "$ncon" = "" ] && ncon=1
# target: 1-wpp_py(56); 2-fpp_neu(58); 3-wpp_vance(48)
target=$3
[ "$target" = "" ] && target=1
#echo "target: $target"
#exit 0

abdir=`dirname $0`
timestamp=`date +%Y%m%d-%H%M%S`
logdir=log_ab
[ -d $logdir ] || mkdir -p $logdir

if [ $target -eq 1 ]; then
	target_name=wpp_py
	ip=192.168.109.56
	port=18080
	urlpath=wlan/distribution
	postfile=$abdir/wpp_req.xml
elif [ $target -eq 2 ]; then
	target_name=fpp_neu
	ip=192.168.109.58
	port=18080
	urlpath=FPP_AD/adapter
	postfile=$abdir/fpp_req.xml
elif [ $target -eq 3 ]; then
	target_name=wpp_vance
	ip=192.168.109.48
	port=8081
	urlpath=wlan/distribution
	postfile=$abdir/wpp_req.xml
else
	echo "Unsupported target id: $target"
	exit 99
fi

gplfile=$logdir/${target_name}_n$1c$2_$timestamp.gpl 
csvfile=$logdir/${target_name}_n$1c$2_$timestamp.csv 
url=http://$ip:$port/$urlpath

echo -e "\nTesting: $target_name: $url\n"
ab -n $ntot -c $ncon -p $postfile -g $gplfile -e $csvfile $url
